name: CI
on:
  push:
  workflow_dispatch:

jobs:
  curl:
    runs-on: windows-latest
    steps:
      - name: Run a one-line script
        shell: bash
        run: command -v curl | tee -a "$GITHUB_STEP_SUMMARY"
