name: CI
on:
  push:
  workflow_dispatch:

jobs:
  curl:
    runs-on: windows-latest
    steps:
      - name: curl
        shell: bash
        run: |
          (
            command -v curl
            curl --version
          ) | tee -a "$GITHUB_STEP_SUMMARY"
